# Generated by Django 5.0 on 2025-02-14 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10000, message='Starting prices for properties must start at $10,000.')], verbose_name='Price')),
                ('location', models.TextField(max_length=1000, verbose_name='Location/Address')),
                ('property_type', models.TextField(max_length=255, verbose_name='Type of property (Condo, house...)')),
                ('bedrooms', models.PositiveSmallIntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveSmallIntegerField(verbose_name='Bathrooms')),
                ('area', models.PositiveSmallIntegerField(verbose_name='Square feet of propertie')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
