# Generated by Django 5.0 on 2025-02-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='properties_pics/', verbose_name='Property high-value picture.'),
        ),
        migrations.AddField(
            model_name='properties',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publication date'),
        ),
    ]
