# Generated by Django 5.0 on 2025-02-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_properties_picture_properties_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='city',
            field=models.TextField(blank=True, max_length=125, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='properties',
            name='country',
            field=models.TextField(blank=True, max_length=125, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='properties',
            name='state',
            field=models.TextField(blank=True, max_length=125, null=True, verbose_name='State/Departamento'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.TextField(max_length=255, verbose_name='Type of property (Condo, House, Apartment...)'),
        ),
    ]
